version: '3.8'
volumes:
  appdata2: 
  dbdata3: 
services:

  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ProjetLiasseFiscale
    volumes:
      - dbdata3:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build: ./app
    ports:
      - "8081:8081"
    
